n_samples: 10 
sequence_length: 500_000 
recombination_rate: 1e-8 
mutation_rate: 1e-8
migration_rate_range: [0.05, 5.0]
population_size_range: [10_000, 100_000]
divergence_time_range: [50_000, 500_000]